tarea2/mysite/blog/urls.py
from django.urls import path
# from . import views
from .views import BlogView, ArticleDetailView
from . import views
urlpatterns = [
    # path('', views.blog, name="blog")
  path('articles', BlogView.as_view(), name="blog"),
  path('article/<int:pk>', ArticleDetailView.as_view(), name="article"),
  path('subscribe/', views.subscribe, name="subscribe"),
  path('like-article/', views.like_article, name='like-article'),
  path('add_comment/', views.add_comment, name='add-comment'),
  path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
  path('delete_article/<int:article_id>/', views.delete_article, name='delete_article'),

]

tarea2/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('resume/', include('resume.urls')),
    path("__reload__/", include("django_browser_reload.urls")),

    path('login/', include('auth_app.urls')),
    path('accounts/', include('allauth.urls')),

    path('useractivitylogs/', include('useractivitylogs.urls')),
]

tarea2/mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.
class Article(models.Model):
  title = models.CharField(max_length=255)
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  category = models.CharField(max_length=255, default="Category")
  date = models.DateField(default=datetime.date.today)
  abstract = models.CharField(max_length=500, default='Abstract of the article')
  reading_time = models.IntegerField(default=5)
  likes = models.IntegerField(default=0)
  body = models.TextField()

  def __str__(self):
    return self.title + ' | ' + str(self.author)
  
class Comment(models.Model):
  name = models.CharField(max_length=255)
  article = models.ForeignKey(Article, on_delete=models.CASCADE)
  comment_date = models.DateField(default=datetime.date.today)
  comment_body = models.TextField()

  def __str__(self):
    return self.name + ' | ' + str(self.article.title)
  
class Subscription(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    FREQUENCY_CHOICES = [
        ('immediate', 'An email at the moment a new article gets published'),
        ('monthly', 'A monthly email regarding the summary of the month\'s new articles'),
    ]
    frequency = models.CharField(max_length=10, choices=FREQUENCY_CHOICES)

    def __str__(self):
        return self.name + ' | ' + self.email

tarea2/mysite/blog/forms.py
from django import forms
from .models import Comment, Subscription

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_body']

class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ['name', 'email', 'frequency']

tarea2/mysite/blog/views.py
from django.contrib.auth.models import Group
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.views.generic import ListView, DetailView
from .models import Article, Comment, Subscription
from .forms import CommentForm, SubscriptionForm
from django.views.decorators.http import require_POST
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from .models import Article
from django.contrib import messages
from django.urls import reverse
from useractivitylogs.models import UserActionLog

class BlogView(ListView):
    model = Article
    template_name = 'blog.html'
    context_object_name = 'articles'
    paginate_by = 5  # Default pagination

    def get_queryset(self):
        order_by = self.request.GET.get('order_by', 'date')
        count = int(self.request.GET.get('count', self.paginate_by))
        query = self.request.GET.get('query', '')

        if query:
            filtered_articles = Article.objects.filter(title__icontains=query)
        else:
            filtered_articles = Article.objects.all()

        if order_by == 'likes':
            filtered_articles = filtered_articles.order_by('-likes')
        else:
            filtered_articles = filtered_articles.order_by('-date')

        return filtered_articles[:count]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order_by = self.request.GET.get('order_by', 'date')
        count = int(self.request.GET.get('count', self.paginate_by))
        query = self.request.GET.get('query', '')

        if query:
            filtered_articles = Article.objects.filter(title__icontains=query)
        else:
            filtered_articles = Article.objects.all()

        if order_by == 'likes':
            filtered_articles = filtered_articles.order_by('-likes')
        else:
            filtered_articles = filtered_articles.order_by('-date')

        filtered_articles = filtered_articles[:count]

        remaining_articles = Article.objects.exclude(id__in=filtered_articles.values_list('id', flat=True))
        user = self.request.user
        user_is_admin = user.is_authenticated and user.groups.filter(name='admin').exists()
        user_is_moderator = user.is_authenticated and user.groups.filter(name='moderator').exists()
        user_is_subscriber = user.is_authenticated and user.groups.filter(name='subscriber').exists()

        context['user_is_admin'] = user_is_admin
        context['user_is_moderator'] = user_is_moderator
        context['user_is_subscriber'] = user_is_subscriber
        context['filtered_articles'] = filtered_articles
        context['remaining_articles'] = remaining_articles
        context['order_by'] = order_by
        context['count'] = count
        context['query'] = query
        return context
    
class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.object  # El artículo actual

        user = self.request.user
        user_is_admin = user.is_authenticated and user.groups.filter(name='admin').exists()
        user_is_moderator = user.is_authenticated and user.groups.filter(name='moderator').exists()
        user_is_subscriber = user.is_authenticated and user.groups.filter(name='subscriber').exists()

        context['comments'] = Comment.objects.filter(article=article).order_by('-comment_date')
        context['form'] = CommentForm()
        context['user_is_admin'] = user_is_admin
        context['user_is_moderator'] = user_is_moderator
        context['user_is_subscriber'] = user_is_subscriber
        return context

    
def Subscribe(request):
    user = request.user
    user_is_admin = user.is_authenticated and user.groups.filter(name='admin').exists()
    user_is_moderator = user.is_authenticated and user.groups.filter(name='moderator').exists()
    user_is_subscriber = user.is_authenticated and user.groups.filter(name='subscriber').exists()
    context = {
        'user_is_admin': user_is_admin,
        'user_is_moderator': user_is_moderator,
        'user_is_subscriber': user_is_subscriber,
    }
    return render(request, 'subscribe.html', context)

@require_POST
@login_required
def like_article(request):
    article_id = request.POST.get('article_id')
    article = get_object_or_404(Article, id=article_id)
    article.likes += 1
    article.save()
    UserActionLog.objects.create(user=request.user, action='like', details=f"Liked article {article_id}")
    return JsonResponse({'likes': article.likes})

@require_POST
@login_required
def add_comment(request):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        article_id = request.POST.get('article_id')
        comment.article = get_object_or_404(Article, id=article_id)
        comment.name = f"{request.user.first_name} {request.user.last_name}" 
        comment.save()

        UserActionLog.objects.create(user=request.user, action='comment_add', details=f"Commented on article {article_id}")

        return JsonResponse({
            'name': comment.name,
            'comment_date': comment.comment_date.strftime('%Y-%m-%d'),
            'comment_body': comment.comment_body
        })
    return JsonResponse({'error': 'Invalid form submission'}, status=400)

def subscribe(request):
    user = request.user
    user_is_admin = user.is_authenticated and user.groups.filter(name='admin').exists()
    user_is_moderator = user.is_authenticated and user.groups.filter(name='moderator').exists()
    user_is_subscriber = user.is_authenticated and user.groups.filter(name='subscriber').exists()
    context = {
        'user_is_admin': user_is_admin,
        'user_is_moderator': user_is_moderator,
        'user_is_subscriber': user_is_subscriber,
    }
    if request.method == 'POST':
        form = SubscriptionForm(request.POST)
        if form.is_valid():
            form.save()
            UserActionLog.objects.create(user=request.user, action='subscribe', details="Subscribed to the blog")
            # # Enviar correo de confirmación
            # send_mail(
            # 'Subscription Confirmation',
            # 'Thank you for subscribing to our blog!',
            # 'from@example.com',
            # [form.cleaned_data['email']],
            # fail_silently=False,
            # )

    else:
        form = SubscriptionForm()
    return render(request, 'subscribe.html', {'form': form, 'context': context})

def delete_comment(request, comment_id):
    if request.method == 'POST':
        comment = get_object_or_404(Comment, id=comment_id)
        comment.delete()

        UserActionLog.objects.create(user=request.user, action='comment_delete', details=f"Deleted comment {comment_id}")

        return JsonResponse({'status': 'success'})
    return JsonResponse({'status': 'failed'}, status=400)

def delete_article(request, article_id):
    if request.method == 'POST':
        article = get_object_or_404(Article, id=article_id)
        article.delete()

        UserActionLog.objects.create(user=request.user, action='post_delete', details=f"Deleted article {article_id}")

        return JsonResponse({'status': 'success', 'redirect_url':reverse('blog')})
    return JsonResponse({'status': 'failed'}, status=400)

tarea2/mysite/blog/templates/subscribe.html
{% load socialaccount %} 
{% load static tailwind_tags %}
<html lang="en" class="scroll-smooth">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/288840f052.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    {% load static %}
    {% tailwind_css %}
</head>
<body>
<!-- NAVBAR -->
<!-- Navbar HTML -->
<div class="pt-10 pb-2 flex justify-between px-10 items-center">
    <div class="flex justify-start">
        <img src="{% static 'imgs/logo.svg' %}" alt="Logo">
    </div>
  
    <div class="hidden md:flex flex-row justify-center space-x-10">
        <a href="{% url 'home' %}" class="font-sans font-normal text-3xl transition duration-300 hover:text-[#FD8C62]">HOME</a>
        <a href="{% url 'blog' %}" class="font-sans font-normal text-3xl transition duration-300 decoration-[#FD8C62] underline underline-offset-8">BLOG</a>
        <a href="{% url 'resume' %}" class="font-sans font-normal text-3xl transition duration-300 hover:text-[#FD8C62]">RESUME</a>
        <a href="{% url 'about' %}" class="font-sans font-normal text-3xl transition duration-300 hover:text-[#FD8C62]">ABOUT</a>
        
        {% if user.is_authenticated %}
        <div class="relative">
            <button id="profile-btn" class="flex items-center space-x-2 focus:outline-none">
                <i class="fas fa-user-circle text-3xl"></i>
            </button>
            <div id="profile-menu" class="hidden absolute right-0 mt-2 w-auto bg-white border border-gray-200 rounded-lg shadow-lg">
                <div class="flex flex-col gap-2 py-3 px-4">
                    <p class="text-gray-900 font-medium text-xl">{{ user.first_name }} {{ user.last_name }}</p>
                    <p class="text-gray-600">
                      {% if user_is_admin %}
                        Admin
                      {% elif user_is_moderator %}
                        Moderator
                      {% elif user_is_subscriber %}
                        Subscriber
                      {% endif %}
                    </p>
                    <p class="text-gray-500 font-light">{{ user.email }}</p>
                </div>
                {% if user_is_admin %} 
                <div class="py-2 border-t border-gray-200 hover:bg-gray-100">
                    <a href="{% url 'action_log' %}" class="block px-4 py-2 text-gray-700">Action log</a>
                </div>
                {% endif %}
                <div class="py-2 border-t border-gray-200 hover:bg-gray-100">
                    <a href="{% url 'account_logout' %}" class="block px-4 py-2 text-gray-700">Log out</a>
                </div>
            </div>
        </div>
        {% else %}
        <a href="{% provider_login_url 'google' %}?next=/" class="font-sans font-normal text-3xl transition duration-300 hover:text-[#FD8C62]">LOG-IN</a>
        {% endif %}
    </div>
  
    <!-- Hamburger Icon -->
    <div class="md:hidden flex items-center">
        <button id="menu-btn" class="focus:outline-none">
            <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
            </svg>
        </button>
    </div>
  </div>
  
  <!-- Mobile Menu -->
  <div id="menu" class="hidden md:hidden flex flex-col space-y-4 mt-4 p-10 bg-white shadow-lg absolute w-full left-0 top-20 z-50">
    {% if user.is_authenticated %}
        <p class="font-sans font-semibold text-3xl text-gray-900">{{ user.first_name }} {{ user.last_name }}</p>
        <p class="font-sans font-normal text-xl text-gray-600">
        {% if context.user_is_admin %}
            Admin
        {% elif context.user_is_moderator %}
            Moderator
        {% elif context.user_is_subscriber %}
            Subscriber
        {% endif %}
        </p>
        <p class="font-sans font-normal text-xl text-gray-500">{{ user.email }}</p>
        <hr class="border-gray-200 w-11/12 mt-4">
    {% endif %}
    <a href="{% url 'home' %}" class="font-sans font-medium text-2xl transition duration-300 hover:text-[#FD8C62]">HOME</a>
    <a href="{% url 'blog' %}" class="font-sans font-medium text-2xl transition duration-300 hover:text-[#FD8C62]">BLOG</a>
    <a href="{% url 'resume' %}" class="font-sans font-medium text-2xl transition duration-300 hover:text-[#FD8C62]">RESUME</a>
    <a href="{% url 'about' %}" class="font-sans font-medium text-2xl transition duration-300 hover:text-[#FD8C62]">ABOUT</a>
    {% if user.is_authenticated %}
      {% if context.user_is_admin %} 
        <a href="{% url 'action_log' %}" class="font-sans font-medium text-2xl transition duration-300 hover:text-[#FD8C62]">ACTION LOG</a>
      {% endif %}
        <hr class="border-gray-200 w-11/12 mt-4">
        <a href="{% url 'account_logout' %}" class="font-sans font-medium text-2xl transition duration-300 hover:text-[#FD8C62]">LOG-OUT</a>
    {% else %}
        <hr class="border-gray-200 w-11/12 mt-4">
        <a href="{% provider_login_url 'google' %}?next=/" class="font-sans font-medium text-2xl transition duration-300 hover:text-[#FD8C62]">LOG-IN</a>
    {% endif %}
  </div>
  <script>
    document.getElementById('menu-btn').addEventListener('click', function() {
      var menu = document.getElementById('menu');
      menu.classList.toggle('hidden');
    });
    
    document.getElementById('profile-btn').addEventListener('click', function(event) {
          var profileMenu = document.getElementById('profile-menu');
          profileMenu.classList.toggle('hidden');
  
          // Ensure the profile menu opens towards the left
          profileMenu.style.right = '0';
          profileMenu.style.left = 'auto';
          profileMenu.style.top = '100%';
      });
  
      // Close the profile menu if clicked outside
      window.addEventListener('click', function(event) {
          var profileMenu = document.getElementById('profile-menu');
          var profileBtn = document.getElementById('profile-btn');
          if (event.target !== profileBtn && !profileBtn.contains(event.target) && !profileMenu.contains(event.target)) {
              profileMenu.classList.add('hidden');
          }
      });
  </script>
    <!-- {% block content %}
  {% endblock content %} -->
<div class="flex justify-center align-center p-20">
  <form method="POST">
    {% csrf_token %}
    <div class="space-y-12">
        <div class="border-b border-gray-900/10 pb-12">
            <h2 class="font-sans text-base font-semibold leading-7 text-gray-900">Join the community</h2>
            <p class="font-sans mt-1 text-sm leading-6 text-gray-600">Subscribe to my blog for insights and latest updates.</p>

            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                <div class="sm:col-span-3">
                    <label for="id_name" class="font-sans block text-sm font-medium leading-6 text-gray-900">Name</label>
                    <div class="mt-2">
                        <input type="text" name="name" id="id_name" autocomplete="given-name" class="font-sans block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#0097A5] sm:text-sm sm:leading-6">
                    </div>
                </div>

                <div class="sm:col-span-4">
                    <label for="id_email" class="font-sans block text-sm font-medium leading-6 text-gray-900">Email address</label>
                    <div class="mt-2">
                        <input id="id_email" name="email" type="email" autocomplete="email" class="font-sans block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#0097A5] sm:text-sm sm:leading-6">
                    </div>
                </div>
            </div>
        </div>

        <div class="border-b border-gray-900/10 pb-12">
            <h2 class="font-sans text-base font-semibold leading-7 text-gray-900">Article Updates</h2>
            <p class="font-sans mt-1 text-sm leading-6 text-gray-600">Stay ahead of the curve: Sign up for the latest news and updates.</p>

            <div class="mt-10 space-y-10">
                <fieldset>
                    <legend class="font-sans text-sm font-semibold leading-6 text-gray-900">Notifications</legend>
                    <p class="font-sans mt-1 text-sm leading-6 text-gray-600">We'll always let you know about new articles. <br> Tailor your experience: Choose your preferred frequency of updates.</p>
                    <div class="mt-6 space-y-6">
                        <div class="flex items-center gap-x-3">
                            <input id="frequency_immediate" name="frequency" type="radio" value="immediate" class="font-sans h-4 w-4 border-gray-300 text-[#0097A5] focus:ring-[#0097A5]">
                            <label for="frequency_immediate" class="font-sans block text-sm font-medium leading-6 text-gray-900">An email at the moment a new article gets published</label>
                        </div>
                        <div class="flex items-center gap-x-3">
                            <input id="frequency_monthly" name="frequency" type="radio" value="monthly" class=" font-sans h-4 w-4 border-gray-300 text-[#0097A5] focus:ring-[#0097A5]">
                            <label for="frequency_monthly" class="font-sans block text-sm font-medium leading-6 text-gray-900">A monthly email regarding the summary of the month’s new articles</label>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>

    <div class="mt-6 flex items-center justify-end gap-x-6">
        <a href="{% url 'blog' %}" class="font-sans text-sm font-semibold leading-6 text-gray-900">Cancel</a>
        <button type="submit" class="font-sans rounded-md bg-[#FD8C62] px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-[#FD8C62]/70 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Save</button>
    </div>
</form>

  </div>
  
   <!-- FOOTER -->
   <div class="p-5 px-20 bg-[#006D77] grid grid-cols-1 md:grid-cols-3 gap-7 shrink-0">
    <!-- First Column -->
    <div class="flex flex-col items-center md:items-start gap-4">
        <div class="flex items-center space-x-2">
            <i class="fa-regular fa-envelope text-white"></i>
            <a class="font-sans font-normal text-s text-white" href="mailto:julian.robertsolano@ucr.ac.cr">julianrobertsolano01@gmail.com</a>
        </div>
        <div class="flex items-center space-x-2">
            <i class="fa-brands fa-github text-white"></i>
            <a class="font-sans font-normal text-s text-white" href="https://github.com/">Julian2603</a>
        </div>
        <div class="flex items-center space-x-2">
            <i class="fa-brands fa-linkedin text-white"></i>
            <a class="font-sans font-normal text-s text-white" href="https://www.linkedin.com/">Julian2603</a>
        </div>
    </div>
    <!-- Second Column -->
    <div class="flex flex-col items-center justify-center gap-2.5">
        <p class="font-sans font-normal text-xl text-white text-center">Let's get in touch!</p>
        <a href="{% url 'contact' %}" class="bg-[#83C5BE] transition duration-300 hover:bg-[#83C5BE]/70 p-1 px-6 rounded-lg font-sans font-medium text-xl text-black shadow-lg">Contact me</a>
    </div>
    <!-- Third Column -->
    <div class="flex flex-col items-center md:items-end gap-1.5">
        <div class="flex justify-center md:justify-end">
            <img class="h-10" src="{% static 'imgs/logo-white.svg' %}">
        </div>
        <div class="text-center md:text-right">
            <p class="font-sans font-normal text-s text-white">Copyright &#169; 2024 Julián Robert Solano. All Rights Reserved.</p>
        </div>
    </div>
</div>
  
</body>
</html>